# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transit.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'transit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtransit.proto\x12\x11transit.telemetry\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n\tOperation\x12\x11\n\tidentidad\x18\x01 \x01(\x05\x12\x11\n\tagency_id\x18\x02 \x01(\t\x12\x0f\n\x07mean_id\x18\x03 \x01(\t\x12\x10\n\x08route_id\x18\x04 \x01(\t\x12\x11\n\tdriver_id\x18\x05 \x01(\t\x12\x38\n\x04type\x18\x06 \x01(\x0e\x32*.transit.telemetry.Operation.OperationType\x12\x10\n\x08\x61\x63\x63uracy\x18\x07 \x01(\x05\x12\x10\n\x08latitude\x18\x08 \x01(\x01\x12\x11\n\tlongitude\x18\t \x01(\x01\x12,\n\x08\x64\x61tetime\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x61ltitude\x18\n \x01(\x01\x12\x0f\n\x07\x62\x65\x61ring\x18\x0b \x01(\x01\x12\r\n\x05speed\x18\x0c \x01(\x01\"K\n\rOperationType\x12\x0c\n\x08INICIADO\x10\x00\x12\x0e\n\nFINALIZADO\x10\x01\x12\x0c\n\x08OPERANDO\x10\x02\x12\x0e\n\nSUSPENDIDO\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATION']._serialized_start=70
  _globals['_OPERATION']._serialized_end=459
  _globals['_OPERATION_OPERATIONTYPE']._serialized_start=384
  _globals['_OPERATION_OPERATIONTYPE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
